spring:
  config:
    import:
      - optional:configserver:https://ecommerce-config-service.onrender.com
      - optional:file:.env[.properties]
  application:
    name: product-service
  profiles:
    active: prod
# logging:
#   level:
#     org:
#       flywaydb: DEBUG
# spring.flyway.logging-level=DEBUG
