spring:
  config:
    import:
      - optional:configserver:http://localhost:8888
      - optional:file:.env[.properties]
  application:
    name: product-service
# logging:
#   level:
#     org:
#       flywaydb: DEBUG
# spring.flyway.logging-level=DEBUG
